name: Build
on: push

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
      - name: Install build deps
        run: |
          sudo apt install -y \
            sed make binutils build-essential gcc g++ bash patch \
            gzip bzip2 perl tar cpio unzip rsync file bc wget \
            python-is-python3 python3 libncurses5-dev git \
            subversion graphviz asciidoc python3-matplotlib
      - name: checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Check tree
        run: tree
      - name: Configure
        run: make licheepi_zero_custom_defconfig
      - name: Build
        run: make -j$(nproc)
      - name: Publish data
        uses: actions/upload-artifact@v2
        with:
          name: Firmware images
          path: |
            buildroot/output/images/rootfs.*
            buildroot/output/images/sdcard.img
